### ISSUE TITLE
Docker Image 자동 빌드

### ISSUE THREAD

**Issue by dwd9999** [HARl803/api-gateway#4]
## Description
- Jenkins를 사용해 Github main 브랜치게 커밋이 들어오는 경우 자동으로 Docker Image를 빌드하여 Docker Hub에 업로드합니다.

## Todo
- [x] Jenkins 라우팅 설정
- [ ] Jenkins 파이프 라인 설정
- [x] mypc 서버 Dockerfile 작성
- [ ] cscenter 서버 Dockerfile 작성
- [ ] auth 서버 Dockerfile 작성
- [ ] notification 서버 Dockerfile 작성
- [ ] webrtc 서버 Dockerfile 작성
- [ ] matching 서버 Dockerfile 작성
- [ ] search 서버 Dockerfile 작성
- [ ] community 서버 Dockerfile 작성
- [ ] bill 서버 Dockerfile 작성
